export const projectsList = [
  
  {
    id: 1,
    name: "Machaon",
    description: "Разработка ИТ‑продуктов",
    screenshot: "/src/assets/images/projects/machaon.jpg",
    stack: ["javascript", "nunjucks", "handlebars", "sass", "webpack"],
    tasks: ["Dart/Light-режимы", "Анимация"],
    url: "https://machaon.ru/",
  },
  {
    id: 2,
    name: "Еврейский музей и центр толерантности",
    description: "Культурно-образовательный проект",
    screenshot: "/src/assets/images/projects/museum.jpg",
    stack: ["javascript", "nunjucks", "sass", "webpack"],
    tasks: ["Покупка билетов", "Инфомат", "SVG-анимация"],
    url: "https://www.jewish-museum.ru/",
  }, 
  {
    id: 3,
    name: "Университет МФЮА",
    description: "Официальный сайт",
    screenshot: "/src/assets/images/projects/mfua.jpg",
    stack: ["javascript", "nunjucks", "handlebars", "sass", "webpack"],
    tasks: ["А также верстка смежных сайтов: <a href='https://rector.mfua.ru/' target='_blank'>ректора МФЮА</a>, <a href='https://idomfua.ru/' target='_blank'>Института дополнительного образования</a>, <a href='https://do.mfua.ru/' target='_blank'>Института заочного обучения</a>, <a href='https://www.mfua.ru/kwu/' target='_blank'>муждународных программ бакалавриата</a>"],
    url: "https://www.mfua.ru/",
  },
  {
    id: 5,
    name: "ЕГЭ hub",
    description: "Онлайн-школа подготовки к экзаменам",
    screenshot: "/src/assets/images/projects/egehub.jpg",
    stack: ["react", "jsx"],
    tasks: ["Верстка на react"],
    url: "https://ege-hub.ru/",
  },
  {
    id: 6,
    name: "X-Fit",
    description: "Сайт фитнес-клуба",
    screenshot: "/src/assets/images/projects/studfit.jpg",
    stack: ["javascript", "nunjucks", "sass", "webpack"],
    tasks: ["Адаптивная и кроссбраузерная верстка сайта"],
    url: "https://studfit.ru/",
  },
  {
    id: 7,
    name: "Франшиза Паника",
    description: "Комнаты квестов по франшизе ",
    screenshot: "/src/assets/images/projects/panika.jpg",
    stack: ["javascript", "handlebars", "sass", "webpack"],
    tasks: ["Анимация при прокрутке страницы (библиотека AOS)", "Разделение javascript кода на chunks"],
    url: "https://fr.panika.org/",
  },
  {
    id: 8,
    name: "Детский технопарк «Наукоград»",
    description: "Официальный сайт подразделения вуза",
    screenshot: "/src/assets/images/projects/naukograd.jpg",
    stack: ["javascript", "handlebars", "sass", "webpack"],
    tasks: ["Адаптивная и кроссбраузерная верстка сайта"],
    url: "https://naukograd.mfua.ru/",
  },
  {
    id: 9,
    name: "Gorenje Russia",
    description: "Локализация официального сайта",
    screenshot: "/src/assets/images/projects/gorenje.jpg",
    stack: ["jquery"],
    tasks: ["Парсинг верстки", "Оптимизация загрузки сайта"],
    url: "https://ru.gorenje.com/",
  },
  {
    id: 10,
    name: "MBA MFUA",
    description: "Бизнес-школа от МФЮА",
    screenshot: "/src/assets/images/projects/mbamfua.jpg",
    stack: ["javascript", "nunjucks", "sass", "webpack"],
    tasks: ["Адаптивная и кроссбраузерная верстка сайта"],
    url: "https://www.mbamfua.ru/",
  },
  {
    id: 11,
    name: "Colvir",
    description: "Корпоративный сайт",
    screenshot: "/src/assets/images/projects/colvir.jpg",
    stack: ["javascript", "jquery"],
    tasks: ["Адаптивная и кроссбраузерная верстка сайта"],
    url: "https://colvir.com/",
  },
  {
    id: 12,
    name: "Pack24",
    description: "Гипермаркет упаковочных материалов",
    screenshot: "/src/assets/images/projects/pack24.jpg",
    stack: ["tailwind"],
    tasks: ["Адаптивная и кроссбраузерная верстка сайта"],
    url: "https://pack24.ru/",
  },
  {
    id: 13,
    name: "Datara",
    description: "Магазин тары и упаковки",
    screenshot: "/src/assets/images/projects/datara.jpg",
    stack: ["jquery", "stylus", "twig"],
    tasks: ["Редизайн сайта"],
    url: "https://datara.ru",
  },
  {
    id: 14,
    name: "Музей «Наука, техника, искусство»",
    description: "Музей университета МФЮА",
    screenshot: "/src/assets/images/projects/mfua_museum.jpg",
    stack: ["javascript", "handlebars", "sass"],
    tasks: ["Адаптивная и кроссбраузерная верстка сайта"],
    url: "https://museum.mfua.ru/",
  },
]